FROM python:3.9
WORKDIR /app
COPY 1_extract_to_mongo.py .
COPY config.py .
COPY config_hidden.ini .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "1_extract_to_mongo.py"]