FROM python:3.9
WORKDIR /app
COPY 2_calculate_trend.py .
COPY config.py .
COPY config_hidden.ini .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "2_calculate_trend.py"]